import re
import streamlit as st

st.set_page_config(
    page_title="MedEvidence-AI V5",
    page_icon="🧬",
    layout="wide"
)

st.title("🧬 MedEvidence-AI V5")
st.subheader("Evidence-backed Clinical Synthesis")

st.markdown(
    """
    **Workflow**

    AI response → Claims → Classification → Evidence →
    Verification → Correction → Final synthesis
    """
)

st.divider()


# --------------------------------------------------
# CLAIM CLASSIFICATION
# --------------------------------------------------

def classify_claim(claim):
    text = claim.lower().strip()

    # Diagnostic claims:
    # Terms specifically associated with diagnosis,
    # confirmation, biopsy or clinical suspicion.
    diagnostic_patterns = [
        r"\bsuspect\b",
        r"\bsuspicion\b",
        r"\bdiagnos(?:is|e|ed|tic)\b",
        r"\bbiopsy\b",
        r"\bhistopatholog(?:y|ical)\b",
        r"\bconfirm(?:ed|ation)?\b",
        r"\bconfirmation\b",
        r"\bstaging\b",
        r"\bstage\b",
        r"\bmetast(?:asis|atic)\b",
        r"\bconsistent with\b",
        r"\bsuggests?\b",
        r"\bindicates?\b",
    ]

    # Recommendations:
    # Terms indicating an action or recommendation.
    recommendation_patterns = [
        r"\bshould\b",
        r"\brecommend(?:ed|ation)?\b",
        r"\bmust\b",
        r"\bconsider\b",
        r"\bavoid\b",
        r"\bdo not\b",
        r"\bis indicated\b",
    ]

    if any(
        re.search(pattern, text)
        for pattern in recommendation_patterns
    ):
        return "Recommendation"

    if any(
        re.search(pattern, text)
        for pattern in diagnostic_patterns
    ):
        return "Diagnostic claim"

    # Statements describing medical facts,
    # characteristics, associations or measurements.
    medical_fact_patterns = [
        r"\bis\b",
        r"\bare\b",
        r"\bhas\b",
        r"\bhave\b",
        r"\bcauses?\b",
        r"\bassociated with\b",
        r"\bspecific\b",
        r"\belevated\b",
        r"\bincreased\b",
        r"\bdecreased\b",
        r"\bpresents?\b",
        r"\bcontains?\b",
        r"\bmeasured\b",
    ]

    if any(
        re.search(pattern, text)
        for pattern in medical_fact_patterns
    ):
        return "Medical fact"

    return "Clinical statement"


# --------------------------------------------------
# 1. AI-GENERATED RESPONSE
# --------------------------------------------------

st.header("1. AI-generated clinical response")

ai_response = st.text_area(
    "Paste the AI-generated medical response:",
    height=220,
    placeholder=(
        "Paste a response generated by ChatGPT, Gemini, Claude, "
        "or another AI system."
    )
)

if st.button("Extract and classify clinical claims"):

    if not ai_response.strip():
        st.warning("Please enter an AI-generated response.")

    else:

        sentences = re.split(
            r"(?<=[.!?])\s+",
            ai_response.strip()
        )

        claims = [
            sentence.strip()
            for sentence in sentences
            if len(sentence.strip()) > 20
        ]

        st.success(
            f"{len(claims)} candidate claim(s) identified."
        )

        st.subheader("Verification queue")

        if claims:

            for index, claim in enumerate(
                claims,
                start=1
            ):

                claim_type = classify_claim(claim)

                st.markdown(
                    f"### Claim {index}"
                )

                st.write(claim)

                st.write(
                    f"**Type:** {claim_type}"
                )

                st.caption(
                    "🔎 Needs independent verification"
                )

        else:

            st.info(
                "No candidate claims were identified."
            )


st.divider()


# --------------------------------------------------
# 2. CLINICAL CLAIM
# --------------------------------------------------

st.header("2. Clinical claim")

claim = st.text_area(
    "Clinical claim to verify:",
    placeholder=(
        "Example: PSA is prostate-specific "
        "but not cancer-specific."
    )
)


# --------------------------------------------------
# 3. EVIDENCE
# --------------------------------------------------

st.header("3. Evidence")

evidence = st.text_area(
    "Relevant passage from the medical source:",
    placeholder=(
        "Paste the exact relevant passage "
        "from the medical source."
    )
)


# --------------------------------------------------
# 4. SOURCE
# --------------------------------------------------

st.header("4. Source")

source = st.text_input(
    "Source name:",
    value=(
        "EAU Guidelines on Prostate Cancer "
        "— Diagnostic Evaluation"
    )
)

version = st.text_input(
    "Version / Year:",
    value="2026"
)

identifier = st.text_input(
    "URL / DOI / PMID:",
    value=(
        "https://uroweb.org/guidelines/"
        "prostatecancer/chapter/diagnostic-evaluation"
    )
)


# --------------------------------------------------
# 5. EVIDENCE ASSESSMENT
# --------------------------------------------------

st.header("5. Evidence assessment")

status = st.selectbox(
    "Verification status:",
    [
        "Supported",
        "Partially supported",
        "Not supported",
        "Source not verified"
    ]
)

assessment = st.text_area(
    "Why does the evidence support, partially support, "
    "or not support the claim?",
    placeholder=(
        "Explain the relationship between "
        "the claim and the evidence."
    )
)


# --------------------------------------------------
# 6. FINAL WORDING
# --------------------------------------------------

st.header("6. Evidence-backed final wording")

final_wording = st.text_area(
    "Corrected final wording:",
    placeholder=(
        "Write the final evidence-backed formulation."
    )
)


# --------------------------------------------------
# GENERATE RECORD
# --------------------------------------------------

if st.button("Generate evidence record"):

    if not claim:
        st.warning(
            "Please enter a clinical claim."
        )

    elif not evidence:
        st.warning(
            "Please provide the relevant evidence passage."
        )

    elif not source:
        st.warning(
            "Please provide the source."
        )

    else:

        st.success(
            "Evidence verification record created."
        )

        st.divider()

        st.subheader(
            "Evidence Verification Record"
        )

        st.markdown("### Claim")
        st.write(claim)

        st.markdown("### Claim type")
        st.write(classify_claim(claim))

        st.markdown("### Evidence passage")
        st.info(evidence)

        st.markdown("### Source")
        st.write(source)

        st.write(
            "**Version / Year:**",
            version
        )

        st.write(
            "**Identifier:**",
            identifier
        )

        st.markdown(
            "### Verification status"
        )

        if status == "Supported":
            st.success("🟢 Supported")

        elif status == "Partially supported":
            st.warning(
                "🟠 Partially supported"
            )

        elif status == "Not supported":
            st.error(
                "🔴 Not supported"
            )

        else:
            st.info(
                "⚪ Source not verified"
            )

        st.markdown(
            "### Evidence assessment"
        )

        if assessment:
            st.write(assessment)
        else:
            st.warning(
                "No assessment provided."
            )

        st.markdown(
            "### Evidence-backed final wording"
        )

        if final_wording:
            st.info(final_wording)
        else:
            st.warning(
                "No final wording provided."
            )

        st.divider()

        st.caption(
            "MedEvidence-AI is an experimental research "
            "and educational prototype. Claim classification "
            "is rule-based and does not determine whether "
            "a medical statement is true or false. Human "
            "review remains necessary."
        )
